# Generated by Django 5.2.7 on 2025-11-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='file',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='api.document'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='api.project'),
        ),
        migrations.AddConstraint(
            model_name='chathistory',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('document__isnull', False), _connector='OR'), name='either_project_or_document_not_null'),
        ),
    ]
